### ISSUE TITLE
Longitude and latitude in local GEOJson seem to be swapped

### ISSUE THREAD

**Issue by SilasPeters** [ichim/LeafletForBlazor-NuGet#2]
In my wwwroot folder, I have the following JSON file:
```json
[
  {
    "type": "feature",
    "geometry": {
      "type": "point",
      "coordinates": [ 54.057122, 6.081795 ]
    },
    "properties": {
      "name": "prachtige rotonde"
    }
  },
  {
    "type": "feature",
    "geometry": {
      "type": "point",
      "coordinates": [ 54.059813, 6.073641 ]
    },
    "properties": {
      "name": "oude wielerbaan"
    }
  }
]
```

The thing is, they end up somewhere in Arabia and not near the Netherlands, where they should be. Google maps and openstreetmap itself do interpret these coordinates correctly.

My guess is that you confused longitude with latitude when interpreting a local GEOJson.

**Comment by ichim** [comment]
Hello sir,

Try to reverse the coordinates.


Thanks a lot for using package

From: Silas Peters ***@***.***>
Sent: Sunday, February 26, 2023 2:22 PM
To: ichim/LeafletForBlazor-NuGet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ichim/LeafletForBlazor-NuGet] Longitude and latitude in local GEOJson seem to be swapped (Issue #2)


In my wwwroot folder, I have the following JSON file:

[

  {

    "type": "feature",

    "geometry": {

      "type": "point",

      "coordinates": [ 54.057122, 6.081795 ]

    },

    "properties": {

      "name": "prachtige rotonde"

    }

  },

  {

    "type": "feature",

    "geometry": {

      "type": "point",

      "coordinates": [ 54.059813, 6.073641 ]

    },

    "properties": {

      "name": "oude wielerbaan"

    }

  }

]

The thing is, they end up somewhere in Arabia and not near the Netherlands, where they should be. Google maps and openstreetmap itself do interpret these coordinates correctly.

My guess is that you confused longitude with latitude when interpreting a local GEOJson. Another reason why I suspect this, is because the sample code provided on the readme on NuGet<https://www.nuget.org/packages/LeafletForBlazor/1.0.6#readme-body-tab> first sets the longitude (y-axis) and then the latitude (x-axis), while normally x comes before y.

**Comment by ichim** [comment]
…a clue for me is that the points fall in the Arab area, so reverse coordinates as in next example:



[

  {

    "type": "feature",

    "geometry": {

      "type": "point",

      "coordinates": [6.081795, 54.057122]

    },

    "properties": {

      "name": "prachtige rotonde"

    }

  },

  {

    "type": "feature",

    "geometry": {

      "type": "point",

      "coordinates": [6.073641, 54.059813,]

    },

    "properties": {

      "name": "oude wielerbaan"

    }

  }

]

Tanks a lot for using package,
Laurentiu Ichim

From: Silas Peters ***@***.***>
Sent: Sunday, February 26, 2023 2:22 PM
To: ichim/LeafletForBlazor-NuGet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ichim/LeafletForBlazor-NuGet] Longitude and latitude in local GEOJson seem to be swapped (Issue #2)


In my wwwroot folder, I have the following JSON file:

[

  {

    "type": "feature",

    "geometry": {

      "type": "point",

      "coordinates": [ 54.057122, 6.081795 ]

    },

    "properties": {

      "name": "prachtige rotonde"

    }

  },

  {

    "type": "feature",

    "geometry": {

      "type": "point",

      "coordinates": [ 54.059813, 6.073641 ]

    },

    "properties": {

      "name": "oude wielerbaan"

    }

  }

]

The thing is, they end up somewhere in Arabia and not near the Netherlands, where they should be. Google maps and openstreetmap itself do interpret these coordinates correctly.

My guess is that you confused longitude with latitude when interpreting a local GEOJson. Another reason why I suspect this, is because the sample code provided on the readme on NuGet<https://www.nuget.org/packages/LeafletForBlazor/1.0.6#readme-body-tab> first sets the longitude (y-axis) and then the latitude (x-axis), while normally x comes before y.
