### ISSUE TITLE
How to move map?

### ISSUE THREAD

**Issue by DaZhiAmbit** [ichim/LeafletForBlazor-NuGet#9]
How to move map?

**Comment by ZARichardWright** [comment]
The moving of the points works great the problem i am having is centering the map around the user selected data. 
ie. when selecting a different log file i want to center the map around the selected data.

**Comment by ZARichardWright** [comment]
Works Perfect Thanks

**Comment by avresial** [comment]
Hi
In order to move map I can use following method.

```c#
public async Task movePoint(double[] coordinate, PointSymbol pointSymbol)
```

Is there any way to zoom in or out using method too?

I tried to change `parameters.zoomLevel` from code. For example using a button. But it seems that it does not affect map at all. Setting `RealTimeMap.LoadParameters` zoom level works only during initialization. 

I tried invoking `InvokeAsync(StateHasChanged);` after zoom value change and it does not work.
